# This GitHub workflow deploys Bundle resources (ML resource config and more)
# defined under databricks_ci_cd/resources/*
# and databricks_ci_cd/databricks.yml with prod deployment target configs,
# when PRs are merged into the release branch
name: Bundle Deployment for databricks_ci_cd Prod

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./databricks_ci_cd

env:
  DATABRICKS_TOKEN: ${{ secrets.PROD_WORKSPACE_TOKEN }}

jobs:
  prod:
    concurrency: databricks_ci_cd-prod-bundle-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@v0.221.0
      - name: Validate Bundle For Prod
        id: validate
        run: |
          databricks bundle validate -t prod
      - name: Deploy Bundle to Prod
        id: deploy
        run: |
          databricks bundle deploy -t prod
      - name: Run Feature Engineering Workflow for Test Deployment Target in Production Workspace
        id: feature_engineering
        run: |
          databricks bundle run write_feature_table_job -t prod
      - name: Run Training Workflow for Test Deployment Target in Production Workspace
        id: training
        run: |
          databricks bundle run model_training_job -t prod 
