name: Bundle validation for databricks_ci_cd

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'databricks_ci_cd/**'

defaults:
  run:
    working-directory: ./databricks_ci_cd/

env:
  STAGING_WORKSPACE_TOKEN: ${{ secrets.STAGING_WORKSPACE_TOKEN }}
  PROD_WORKSPACE_TOKEN: ${{ secrets.PROD_WORKSPACE_TOKEN }}

jobs:
  staging:
    concurrency: databricks_ci_cd-staging-bundle-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - uses: databricks/setup-cli@v0.221.0
      - name: Validate Bundle For Staging
        id: validate
        env:
          DATABRICKS_TOKEN: ${{ env.STAGING_WORKSPACE_TOKEN }}
        run: |
          databricks bundle validate -t staging > ../validate_output.txt
      - name: Create Comment with Bundle Configuration
        if: github.event.pull_request
        uses: actions/github-script@v6
        id: comment
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const fileContents = fs.readFileSync('validate_output.txt', 'utf8');
            const output = `#### Bundle Staging Config Validated 🖌
            <details><summary>Staging Validation Output</summary>

            \`\`\`\n
            ${fileContents}
            \`\`\`

            </details>`

            // Ensure context.issue.number is valid before posting comment
            if (context.issue && context.issue.number) {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
              });
            } else {
              console.error('Issue number not found in context.');
            }

  prod:
    concurrency: databricks_ci_cd-prod-bundle-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - uses: databricks/setup-cli@v0.221.0
      - name: Validate Bundle For Prod
        id: validate
        env:
          DATABRICKS_TOKEN: ${{ env.PROD_WORKSPACE_TOKEN }}
        run: |
          databricks bundle validate -t prod > ../validate_output.txt
      - name: Create Comment with Bundle Configuration
        if: github.event.pull_request
        uses: actions/github-script@v6
        id: comment
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const fileContents = fs.readFileSync('validate_output.txt', 'utf8');
            const output = `#### Bundle Prod Config Validated 🖌
            <details><summary>Prod Validation Output</summary>

            \`\`\`\n
            ${fileContents}
            \`\`\`

            </details>`

            // Ensure context.issue.number is valid before posting comment
            if (context.issue && context.issue.number) {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
              });
            } else {
              console.error('Issue number not found in context.');
            }
